apiVersion: v1
kind: ConfigMap
metadata:
  name: iter8-traffic
data:
  config.yaml: |
    defaultResync: 15m
    image: iter8/iter8:0.13
    logLevel: info
    resourceTypes:
      deploy:
        Group: apps
        Resource: deployments
        Version: v1
      isvc:
        Group: serving.kserve.io
        Resource: inferenceservices
        Version: v1beta1
      svc:
        Group: ""
        Resource: services
        Version: v1
      vs:
        Group: networking.istio.io
        Resource: virtualservices
        Version: v1beta1
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 250m
        memory: 64Mi