categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ğŸ§¹ Cleaned or removed features'
    label: 'remove'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ğŸ§° Maintenance'
    label: 'chore'
  - title: 'ğŸ“ Documentation'
    labels:
      - 'doc'
      - 'documentation'
  - title: 'ğŸš¦ Tests'
    labels:
      - 'test'
      - 'tests'
change-template: '- #$NUMBER: $TITLE'
template: |
  ## Whatâ€™s Changed
  $CHANGES
