name-template: 'Official release of Iter8 version $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
- title: 'ğŸš€ Features'
  labels:
  - 'kind/enhancement'
- title: 'ğŸ§¹ Cleaned or removed features'
  label: 'remove'
- title: 'ğŸ› Bug Fixes'
  labels:
  - 'kind/bug'
- title: 'ğŸ§° Maintenance'
  label: 'chore'
- title: 'ğŸ“ Documentation'
  labels:
  - 'kind/docs'
- title: 'ğŸš¦ CI'
  labels:
  - 'area/CI'
change-template: '- #$NUMBER: $TITLE'
template: |
  ## Whatâ€™s Changed
  $CHANGES
