apiVersion: v2
name: iter8lib
version: 0.9.2
description: Iter8 library chart
type: library
home: https://iter8.tools
sources:
- https://github.com/iter8-tools/iter8
maintainers:
- name: Srinivasan Parthasarathy
  email: spartha@us.ibm.com
  url: https://researcher.watson.ibm.com/researcher/view.php?person=us-spartha
icon: https://github.com/iter8-tools/iter8/raw/master/mkdocs/docs/images/favicon.png
appVersion: v0.9
