### iter8Image default iter8 image used for running Kubernetes experiments
iter8Image: iter8/iter8:0.10

### majorMinor is the minor version of Iter8
majorMinor: v0.10

### enable to use job or a cronjob
### For example:
###   runner: job
### Or:
###   runner: cronjob
runner: none