resources:
- configmap.yaml
- headlessservice.yaml
- role.yaml
- rolebinding.yaml
- serviceaccount.yaml
- statefulset.yaml

commonLabels:
  app.kubernetes.io/name: traffic
  app.kubernetes.io/instance: iter8-traffic
  app.kubernetes.io/version: v0.14
