### Parameters of the the load-test-http experiment chart and the default values.

##################################

### This chart accepts all parameters that are part of the collectHTTPInputs struct.
### https://github.com/iter8-tools/iter8/blob/2891c13aac668bd651cc8e76f2d11a9d9a4fb75b/base/collect_http.go#L25
### In particular, the json tags of the struct fields correspond to chart parameter names.
### For example, url, numRequests, and qps.
### The default values of the parameters are also documented in the link above.

### In addition, this chart supports the following parameters.

### payloadUrl    URL of payload. If this field is specified, 
### Iter8 will send HTTP POST requests to versions with 
### data downloaded from this URL as the payload.
# payloadURL: null

### SLOs    A map of service level objectives (SLOs) that the app needs to satisfy.
### Metrics collected during the load test are used to verify if the app satisfies SLOs.
### Each SLO has a key which is the metric name, 
### and a value which is the upper limit on the metric.
### Valid metric names are error-rate, error-count, latency-max, 
### latency-mean, latency-stddev, and latency-pX, where X is any latency percentile 
### (i.e., any float value between 0 and 100).
### Unit of latency is msec.
### Example:
###   http/error-rate: 0
###   http/latency-mean: 50
###   http/latency-p99: 200
# SLOs: null
