name: build local and serve local docs

on:
  pull_request:
    paths:
    - 'mkdocs/**'
    - 'src/**'
    - 'package-lock.json'
    - 'package.json'

env:
  NODE_VERSION: 15.x
  PYTHON_VERSION: 3.x

jobs:
  document:
    name: Build and serve local docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js runtime
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Set up Node.js dependencies and build material theme
      run: | 
        npm install && npm run build

    - name: Set up Python runtime
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python dependencies
      run: |
        cd mkdocs
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and serve
      run: |
        cd mkdocs
        mkdocs build -s
        mkdocs serve -s &

    - name: Check for broken links
      id: link-report
      uses: celinekurpershoek/link-checker@v1.0.1
      with:
        # Required:
        url: 'http://localhost:8000'
        # honorRobotExclusions: false
        recursiveLinks: true # Check all URLs on all reachable pages (could take a while)

    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"
