name: Mike versioning

on:
  release:
    types: [published]

env:
  PYTHON_VERSION: 3.9

jobs:
  push-doc-version:
    name: Push doc version
    runs-on: ubuntu-latest
    steps:
    # setup pre-reqs
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch all commits/branches      
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    # create
    - name: Create new version
      run: |
        git config --global user.name "Srinivasan Parthasarathy"
        git config --global user.email spartha@us.ibm.com  
        cd mkdocs
        pip install --upgrade pip
        pip install -r requirements.txt
        mike deploy ${{ github.event.inputs.version }} vtest1.3.0 -p -u
